language: sh

before_script:
        - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.4.4-4_amd64.deb"
        - sudo dpkg -i "shellcheck_0.4.4-4_amd64.deb"

script:
        - shellcheck weatherspeaker
